name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and test in Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        target: test
        push: false

  docker-prod:
    runs-on: ubuntu-latest
    needs: docker-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push prod image
      uses: docker/build-push-action@v4
      with:
        context: .
        target: prod
        push: true
        tags: julianbvw/task-manager:latest
  
  deploy-staging:
    runs-on: ubuntu-latest
    needs: docker-prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Trigger Render deploy
      run: |
        curl "${{ secrets.RENDER_DEPLOY_HOOK }}"

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: https://cicd-task-manager-prod.onrender.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Trigger Render Production deploy
      run: |
        curl "${{ secrets.RENDER_PROD_DEPLOY_HOOK }}"